manubot/catalog

.gitignore
.travis.yml
README.md
catalog.yml
deploy.sh
process-catalog.py

Basic catalog processing and CI

---

catalog.yml

Refs https://github.com/manubot/catalog/issues/6

Add FIAR metrics manuscript to catalog

---

README.md
catalog.yml

Closes https://github.com/manubot/catalog/issues/15
Also fixed some typos in the README.

Add biological priors manuscript to Manubot catalog

---

.travis.yml
README.md
process-catalog.py

closes https://github.com/manubot/catalog/issues/10

Extract thumbnail_url from HTML <head>

---

catalog.yml
process-catalog.py

work in progress... more manuscripts on the way

Remove thumbnail_url for manuscripts that now set them in HTML <meta>

---

catalog.yml

Add link to in-progress paper: https://github.com/czbiohub/orthology-free-comparative-transcriptomics-paper/projects/1

Add in-progress paper

---

catalog.yml

Michael Zietz and Nicholas P. Tatonetti
https://zietzm.com/abo_covid/
https://www.medrxiv.org/content/10.1101/2020.04.08.20058073v1

Add COVID blood group preprint

---

catalog.yml

@adebali I didn't see an HTML version of your manuscript anywhere for us to link in the Manubot catalog.  Is that correct?

Add comparative primate manuscript

---

catalog.yml

Sorry about doing 2 PRs in a row. I just received the email from ChemRxiv today

Add preprint DOI for "Extension of Roles in the ChEBI Ontology"

---

catalog.yml

Title: Reproducible, portable, and efficient ancient genome reconstruction with nf-core/eager
Corresponding author: @apeltzer
BioRxiv DOI: https://doi.org/10.1101/2020.06.11.145615
Manubot repo: https://github.com/apeltzer/eager2-paper/
Manubot rendered: https://apeltzer.github.io/eager2-paper

Add nf-core/eager preprint

---

catalog.yml

There's an accompanying [blog post](https://sagebionetworks.org/in-the-news/bringing-structure-and-design-to-data-governance/) too

Add governanceGreenPaper

---

catalog.yml

The manuscript itself was collaboratively written on https://www.manuscripts.io/ since I wasn't able to teach `git` to my co-authors in time, but the submitted copy was generated with `manubot`.

Manuscript on microCT scans & analysis of teeth

---

catalog.yml

Hello, 
We still do not have it as a full preprint, with a DOI and such. Is it an acceptable contribution anyways?
Best,
Tiago

Update catalog.yml with a eLifeSprint 2020 report

---

catalog.yml

Hello, @dhimmel , 
Do I have to add anything more or did I get it right? 
Best,
Tiago

Add study on definition of cell types

---

catalog.yml

The manuscript was written on Authorea, but for 'posteriority' I migrated it to a Manubot-repository.
The repository is also used to work on the revisions of the manuscript.

Manuscript analysing changes in pulmonary acini

---

catalog.yml

Tooth manuscript is accepted and published

---

.github/workflows/build.yaml
requirements.txt

refs https://github.com/manubot/catalog/issues/48
Will merge this since it's hard to test otherwise.

GitHub Actions workflow

---

catalog.yml

Rebrand! Closes https://github.com/trangdata/tpot-fss-ms/issues/13

Fix broken links

---

catalog.yml

Perhaps the response from https://api.crossref.org/v1/works/10.1186%2Fs13059-022-02705-y/transform indicates we need to wait to merge this

Journal citation for mpmp manuscript

---

catalog.yml

It's a manuscript written about the tomographic data collection on a large corpus of Cichlids.
I also 'sorted' my contributions to the catalog.

Add new manuscript

---

catalog.yml

catalog: adafede thesis
